### ISSUE TITLE
I added to plugin folder and it does not work

### ISSUE THREAD

**Issue by MannyFlapjack** [EliteKits/Christian-Minecraft-Server#1]
I added to my plugins folder
onlyplugins i have is skript and stuff pls fix

**Comment by dblucc** [comment]
Well U May Need to Also Have The Following Plugins on ur Server:
- WorldEdit
- PermissionsEx
- Vault
- Essentials
- Multiverse-Core
- Holographic Displays
- Citizens
- AuthMe Reloaded
- Shopkeepers
- SilkSpawners
- VoxelSniper
- Colored Tags
- Chest Shop
- CommandNPC
- SetSpawn
- PlugMan
- ASkyblock
- Skript
- ProtocolLib
- Multiworld
- Factions
- NoCheatPlus
- ChatEx
- JI
- Janitor
- OpenInv
- Bedwars
- Dynmap

Try Now

**Comment by MannyFlapjack** [comment]
Oh I did not have AuthMe Reloaded
